stages:
- build-image
- deploy-dev
- deploy-test
- deploy-production

default:
  tags:
  - openshift

variables:
  # App Build Settings
  APP_BUILD_DIRECTORY: .

  # Openshift Settings
  OPENSHIFT_APP_NAME: riski-extraktor
  OPENSHIFT_BRANCH_INTEGRATION: "true"
  OPENSHIFT_TEST_TOKEN: $OPENSHIFT_K_TOKEN
  # OPENSHIFT_DEV_NAMESPACE: TODO 
  OPENSHIFT_DEV_ENV: dev
  # OPENSHIFT_TEST_NAMESPACE: TODO
  OPENSHIFT_TEST_ENV: test
  # OPENSHIFT_PROD_NAMESPACE: TODO
  OPENSHIFT_PROD_ENV: prod
  SKIP_DEPLOYMENT: "true"

include:
# Für Branch Pipelines
- template: "Workflows/Branch-Pipelines.gitlab-ci.yml"
- project: "kicc/gitlab-runner-templates"
  ref: "main"
  file:
  # Openshift Image Build über S2I (stage: build-image) 
  - "Openshift-CI.gitlab-ci.yml"
  # Deployment (Rollout) in Dev (stage: deploy-dev), in Test (stage: deploy-test) und in Prod (stage: deploy-prod)
  - "Openshift-CD.gitlab-ci.yml"
