erDiagram
    agenda_item ||--o{ agendaitem_keyword : FK
    agenda_item ||--o{ consultation : FK
    agenda_item ||--o{ file_agenda : FK
    agenda_item ||--o{ meeting_agenda_item : FK
    body ||--o{ body_keyword : FK
    body ||--o{ equivalent_bodies : FK
    body ||--o{ equivalent_bodies : FK
    body ||--o{ location_bodies : FK
    body ||--o{ system : FK
    consultation ||--o{ consultationkeywordlink : FK
    file ||--o{ agenda_item : FK
    file ||--o{ file_agenda : FK
    file ||--o{ file_derivative_link : FK
    file ||--o{ file_derivative_link : FK
    file ||--o{ file_keyword : FK
    file ||--o{ file_meeting : FK
    file ||--o{ file_paper : FK
    file ||--o{ meeting : FK
    file ||--o{ meeting : FK
    file ||--o{ meeting : FK
    file ||--o{ meeting_aux_file : FK
    file ||--o{ paper : FK
    file ||--o{ paper_file : FK
    keyword ||--o{ agendaitem_keyword : FK
    keyword ||--o{ body_keyword : FK
    keyword ||--o{ consultationkeywordlink : FK
    keyword ||--o{ file_keyword : FK
    keyword ||--o{ legislative_term_keyword : FK
    keyword ||--o{ location_keyword : FK
    keyword ||--o{ meeting_keyword : FK
    keyword ||--o{ membership_keyword : FK
    keyword ||--o{ organization_keyword : FK
    keyword ||--o{ paper_keyword : FK
    keyword ||--o{ person_keyword : FK
    legislative_term ||--o{ legislative_term_keyword : FK
    location ||--o{ location_bodies : FK
    location ||--o{ location_keyword : FK
    location ||--o{ location_meetings : FK
    location ||--o{ location_organizations : FK
    location ||--o{ location_papers : FK
    location ||--o{ location_persons : FK
    location ||--o{ meeting : FK
    location ||--o{ organization : FK
    location ||--o{ paper_location : FK
    location ||--o{ person : FK
    meeting ||--o{ agenda_item : FK
    meeting ||--o{ consultation : FK
    meeting ||--o{ file_meeting : FK
    meeting ||--o{ location_meetings : FK
    meeting ||--o{ meeting_agenda_item : FK
    meeting ||--o{ meeting_aux_file : FK
    meeting ||--o{ meeting_keyword : FK
    meeting ||--o{ meeting_organization : FK
    meeting ||--o{ meeting_participant : FK
    meeting ||--o{ organization : FK
    membership ||--o{ membership_keyword : FK
    membership ||--o{ organization_membership : FK
    membership ||--o{ person_membership : FK
    organization ||--o{ location_organizations : FK
    organization ||--o{ meeting_organization : FK
    organization ||--o{ membership : FK
    organization ||--o{ organization : FK
    organization ||--o{ organization_keyword : FK
    organization ||--o{ organization_membership : FK
    organization ||--o{ organization_post : FK
    organization ||--o{ organization_sub_organization : FK
    organization ||--o{ organization_sub_organization : FK
    organization ||--o{ paper_direction_link : FK
    organization ||--o{ paper_originator_organization : FK
    organization ||--o{ post : FK
    organization_type ||--o{ organization : FK
    paper ||--o{ consultation : FK
    paper ||--o{ file_paper : FK
    paper ||--o{ location_papers : FK
    paper ||--o{ paper_Originator_person : FK
    paper ||--o{ paper_direction_link : FK
    paper ||--o{ paper_file : FK
    paper ||--o{ paper_keyword : FK
    paper ||--o{ paper_location : FK
    paper ||--o{ paper_originator_organization : FK
    paper ||--o{ paper_related_paper : FK
    paper ||--o{ paper_related_paper : FK
    paper ||--o{ paper_subordinated_paper : FK
    paper ||--o{ paper_subordinated_paper : FK
    paper ||--o{ paper_superordinated_paper : FK
    paper ||--o{ paper_superordinated_paper : FK
    paper_subtype ||--o{ paper : FK
    paper_type ||--o{ paper : FK
    paper_type ||--o{ paper_subtype : FK
    person ||--o{ location_persons : FK
    person ||--o{ meeting_participant : FK
    person ||--o{ paper_Originator_person : FK
    person ||--o{ person_keyword : FK
    person ||--o{ person_membership : FK
    person ||--o{ person_title : FK
    post ||--o{ organization_post : FK
    system ||--o{ system_other_oparl_version : FK
    system ||--o{ system_other_oparl_version : FK
    title ||--o{ person : FK
    title ||--o{ person_title : FK

    agenda_item {
        INTEGER db_id
        VARCHAR id
        VARCHAR type
        INTEGER meeting
        VARCHAR number
        INTEGER order
        VARCHAR name
        BOOLEAN public
        VARCHAR result
        VARCHAR resolutionText
        INTEGER resolutionFile
        TIMESTAMP start
        TIMESTAMP end
        VARCHAR license
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
        BOOLEAN deleted
    }
    agendaitem_keyword {
        INTEGER agendaitem_id
        INTEGER keyword
    }
    body {
        INTEGER db_id
        VARCHAR id
        VARCHAR type
        VARCHAR name
        VARCHAR shortName
        VARCHAR system
        VARCHAR website
        VARCHAR license
        TIMESTAMP licenseValidSince
        TIMESTAMP oparlSince
        VARCHAR ags
        VARCHAR rgs
        VARCHAR contactEmail
        VARCHAR contactName
        VARCHAR organization
        VARCHAR person
        VARCHAR meeting
        VARCHAR paper
        VARCHAR legislativeTerm
        VARCHAR agendaItem
        VARCHAR file
        VARCHAR locationList
        VARCHAR legislativeTermList
        VARCHAR membership
        VARCHAR classification
        VARCHAR location
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
        BOOLEAN deleted
    }
    body_keyword {
        INTEGER body_id
        INTEGER keyword
    }
    consultation {
        INTEGER db_id
        VARCHAR id
        VARCHAR url
        INTEGER paper
        INTEGER agenda_item
        INTEGER meeting
        BOOLEAN authoritative
        VARCHAR role
        VARCHAR license
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
    }
    consultationkeywordlink {
        INTEGER consultation_id
        INTEGER keyword_id
    }
    equivalent_bodies {
        INTEGER body_id_a
        INTEGER body_id_b
    }
    file {
        INTEGER db_id
        VARCHAR id
        VARCHAR type
        VARCHAR name
        VARCHAR fileName
        VARCHAR mimeType
        TIMESTAMP date
        INTEGER size
        VARCHAR sha1Checksum
        VARCHAR sha512Checksum
        VARCHAR text
        VARCHAR accessUrl
        VARCHAR downloadUrl
        VARCHAR externalServiceUrl
        VARCHAR masterFile
        VARCHAR fileLicense
        VARCHAR license
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
        BOOLEAN deleted
    }
    file_agenda {
        INTEGER file_id
        INTEGER agendaItem
    }
    file_derivative_link {
        INTEGER file_id
        INTEGER derivative_file_id
    }
    file_keyword {
        INTEGER file_id
        INTEGER keyword
    }
    file_meeting {
        INTEGER file_id
        INTEGER meeting_id
    }
    file_paper {
        INTEGER file_id
        INTEGER paper_id
    }
    keyword {
        INTEGER db_id
        VARCHAR name
    }
    legislative_term {
        INTEGER db_id
        VARCHAR id
        VARCHAR type
        VARCHAR body
        VARCHAR name
        TIMESTAMP startDate
        TIMESTAMP endDate
        VARCHAR license
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
        BOOLEAN deleted
    }
    legislative_term_keyword {
        INTEGER legislative_term_id
        INTEGER keyword
    }
    location {
        INTEGER db_id
        VARCHAR id
        VARCHAR type
        VARCHAR description
        JSON geojson
        VARCHAR streetAddress
        VARCHAR room
        VARCHAR postalCode
        VARCHAR subLocality
        VARCHAR locality
        VARCHAR license
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
        BOOLEAN deleted
    }
    location_bodies {
        INTEGER location_id
        INTEGER body_id
    }
    location_keyword {
        INTEGER location_id
        INTEGER keyword
    }
    location_meetings {
        INTEGER location_id
        INTEGER meeting_id
    }
    location_organizations {
        INTEGER location_id
        INTEGER organization_id
    }
    location_papers {
        INTEGER location_id
        INTEGER paper_id
    }
    location_persons {
        INTEGER location_id
        INTEGER person_id
    }
    meeting {
        INTEGER db_id
        VARCHAR id
        VARCHAR type
        VARCHAR name
        VARCHAR meetingState
        BOOLEAN cancelled
        TIMESTAMP start
        TIMESTAMP end
        INTEGER location
        INTEGER invitation
        INTEGER resultsProtocol
        INTEGER verbatimProtocol
        VARCHAR license
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
        BOOLEAN deleted
    }
    meeting_agenda_item {
        INTEGER id
        INTEGER meeting_id
        INTEGER agenda_item_id
    }
    meeting_aux_file {
        INTEGER id
        INTEGER meeting_id
        INTEGER file_id
    }
    meeting_keyword {
        INTEGER meeting_id
        INTEGER keyword
    }
    meeting_organization {
        INTEGER meeting_id
        INTEGER organization_id
    }
    meeting_participant {
        INTEGER id
        INTEGER meeting_id
        INTEGER person_name
    }
    membership {
        INTEGER db_id
        VARCHAR id
        VARCHAR type
        INTEGER organization
        VARCHAR role
        BOOLEAN votingRight
        TIMESTAMP startDate
        TIMESTAMP endDate
        VARCHAR onBehalfOf
        VARCHAR license
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
        BOOLEAN deleted
    }
    membership_keyword {
        INTEGER membership_id
        INTEGER keyword
    }
    organization {
        INTEGER db_id
        VARCHAR id
        VARCHAR type
        VARCHAR body
        VARCHAR name
        INTEGER meeting_id
        VARCHAR shortName
        INTEGER subOrganizationOf
        VARCHAR classification
        TIMESTAMP startDate
        TIMESTAMP endDate
        VARCHAR website
        INTEGER location
        VARCHAR externalBody
        VARCHAR license
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
        BOOLEAN deleted
        INTEGER organization_type_id
    }
    organization_keyword {
        INTEGER organization_id
        INTEGER keyword
    }
    organization_membership {
        INTEGER organization_id
        INTEGER membership_id
    }
    organization_post {
        INTEGER organization_id
        INTEGER post_str
    }
    organization_sub_organization {
        INTEGER organization_id
        INTEGER sub_organization_id
    }
    organization_type {
        INTEGER db_id
        VARCHAR name
        VARCHAR description
    }
    paper {
        INTEGER db_id
        VARCHAR id
        VARCHAR type
        VARCHAR body
        VARCHAR name
        VARCHAR reference
        TIMESTAMP date
        VARCHAR paperType
        INTEGER mainFile
        VARCHAR license
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
        BOOLEAN deleted
        INTEGER paper_type
        INTEGER paper_subtype
    }
    paper_Originator_person {
        INTEGER paper_id
        INTEGER person_name
    }
    paper_direction_link {
        INTEGER paper_id
        INTEGER direction_name
    }
    paper_file {
        INTEGER paper_id
        INTEGER file_id
    }
    paper_keyword {
        INTEGER paper_id
        INTEGER keyword
    }
    paper_location {
        INTEGER paper_id
        INTEGER location_id
    }
    paper_originator_organization {
        INTEGER paper_id
        INTEGER organization_name
    }
    paper_related_paper {
        INTEGER from_paper_id
        INTEGER to_paper_id
    }
    paper_subordinated_paper {
        INTEGER paper_id
        INTEGER subordinated_paper_url
    }
    paper_subtype {
        INTEGER id
        VARCHAR name
        INTEGER paper_type_id
    }
    paper_superordinated_paper {
        INTEGER paper_id
        INTEGER superordinated_paper_url
    }
    paper_type {
        INTEGER id
        VARCHAR name
    }
    person {
        INTEGER db_id
        VARCHAR id
        VARCHAR type
        VARCHAR body
        VARCHAR name
        VARCHAR familyName
        VARCHAR givenName
        VARCHAR formOfAddress
        VARCHAR affix
        VARCHAR gender
        INTEGER location
        VARCHAR life
        VARCHAR lifeSource
        VARCHAR license
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
        BOOLEAN deleted
        INTEGER title
        JSON phone
        JSON email
        JSON status
    }
    person_keyword {
        INTEGER person_id
        INTEGER keyword
    }
    person_membership {
        INTEGER person_id
        INTEGER membership_id
    }
    person_title {
        INTEGER person_id
        INTEGER title_id
    }
    post {
        INTEGER db_id
        VARCHAR name
        INTEGER organization_id
    }
    system {
        INTEGER db_id
        VARCHAR id
        VARCHAR type
        VARCHAR oparlVersion
        VARCHAR otherOparlVersions
        VARCHAR license
        INTEGER body
        VARCHAR name
        VARCHAR contactEmail
        VARCHAR contactName
        VARCHAR website
        VARCHAR vendor
        VARCHAR product
        TIMESTAMP created
        TIMESTAMP modified
        VARCHAR web
        BOOLEAN deleted
    }
    system_other_oparl_version {
        INTEGER system_id
        INTEGER other_version_id
    }
    title {
        INTEGER db_id
        VARCHAR title
    }