---
title: RIS Internet
---

erDiagram

    STR_SITZUNG {
        string sitzungs_id
        date datum
        string art
        Status status
        boolean protokoll_verfuegbar
        date verfuegungsdatum
        string sitzungsort
        MITGLIEDER vorsitz
        date abgeschlossen_am
        string zustaendiges_Referat
        MITGLIEDER ReferentIn
        STR_SITZUNG letze_Sitzung
        STR_SITZUNG naechste_Sitzung
        TAGESORDNUNGSPUNKT tagesordnung
        string historie
    }

    TAGESORDNUNGSPUNKT {
        string top_id
        string sitzungs_id
        string nummer
        string titel
        string kategorie
        string zustaendiger_ausschuss
        Status status
    }

    VORGANG {
        string vorgang_id
        string betreff
        Status status
        date startdatum
        string wahlperiode
        string typ
        string bezirksausschuss
        string ergebnis
        string historie
    }

    DOKUMENT {
        string dokument_id
        string name
        string dateiformat
        string groesse
    }

    ANTRAG {
        string antrags_id
        string betreff
        date erstellt_am
        date regestriert_am
        string wahlperiode
        string gestellt_von
        MITGLIEDER initiative
        string zustaendiges_Referat
        string art
        string typ
        string bearbeitungsart
        date bearbeotinungsfrist
        date erledigt_am
        DOKUMENT dokumente
        string ergebnis
        string historie
    }
    BV_Empfehlung {
        string bv_id
        string betreff
        date beschlossen_am
        date regestriert_am
        string wahlperiode
        string stadtbezirk
        string zustaendiges_Referat
        string art
        string typ
        string bearbeotungsart
        date bearbeotinungsfrist
        date fristverlaengerung
        string ergebnisse
        string historie
        DOKUMENT dokumente
    }
    SITZUNGSVORLAGE{
        string vorlagen_id
        string betreff
        string kurzinformationen
        date freigabe
        string wahlperiode
        string zustaendiges_Referat
        MITGLIEDER ReferentIn
        string art
        string typ
        DOKUMENT dokumente
        string ergebnisse
        string historie
    }
    AUSSCHUSS {
        string ausschuss_id
        string name
        string zustaendigkeit
        MITGLIEDER mitglieder
    }

    MITGLIEDER {
        string name
        string fraktion
    }

%% Beziehungen
    AUSSCHUSS ||--o{ MITGLIEDER : "hat"

    STR_SITZUNG ||--o{ TAGESORDNUNGSPUNKT : "enthaelt"

    TAGESORDNUNGSPUNKT ||--o{ SITZUNGSVORLAGE : "hat"
    TAGESORDNUNGSPUNKT ||--o{ BV_Empfehlung: "hat"
    TAGESORDNUNGSPUNKT ||--o{ VORGANG : "hat"

    TAGESORDNUNGSPUNKT ||--o{ ANTRAG : "hat"

    ANTRAG||--o{ DOKUMENT : "hat"
    STR_SITZUNG ||--o{ DOKUMENT : "hat"
    TAGESORDNUNGSPUNKT ||--o{ DOKUMENT : "hat"
    SITZUNGSVORLAGE ||--o{ DOKUMENT : "hat"
    BV_Empfehlung ||--o{ DOKUMENT : "hat"
    TAGESORDNUNGSPUNKT ||--o{ DOKUMENT : "hat"